import { LoggerCreateDTO, LoggerCreateRawDto } from '../dto/logger.dto';

export interface ILoggerService {
    info({
        action,
        description,
        apiKey,
        userId,
        method,
        requestId,
        roleId,
        type,
        params,
        bodies,
        path,
        statusCode,
        tags,
    }: LoggerCreateDTO);
    debug({
        action,
        description,
        apiKey,
        userId,
        method,
        requestId,
        roleId,
        type,
        params,
        bodies,
        path,
        statusCode,
        tags,
    }: LoggerCreateDTO);
    warn({
        action,
        description,
        apiKey,
        userId,
        method,
        requestId,
        roleId,
        type,
        params,
        bodies,
        path,
        statusCode,
        tags,
    }: LoggerCreateDTO);
    fatal({
        action,
        description,
        apiKey,
        userId,
        method,
        requestId,
        roleId,
        type,
        params,
        bodies,
        path,
        statusCode,
        tags,
    }: LoggerCreateDTO);
    raw({
        level,
        action,
        description,
        apiKey,
        userId,
        method,
        requestId,
        roleId,
        type,
        params,
        bodies,
        path,
        statusCode,
        tags,
    }: LoggerCreateRawDto);
}
