export enum ENUM_RBAC_PERMISSION_STATUS_CODE_ERROR {
    PERMISSION_NOT_FOUND_ERROR = 6100,
    PERMISSION_TYPE_INVALID_ERROR = 6101,
    PERMISSION_EXIST_ERROR = 6102,
    PERMISSION_IS_ACTIVE_ERROR = 6103,
    PERMISSION_INACTIVE_ERROR = 6104,
    PERMISSION_USED_ERROR = 6105,
}
